### ISSUE TITLE
Discover of custom characteristic issue on Windows

### ISSUE THREAD

**Issue by Regular89** [Navideck/universal_ble#29] opened 2024-03-20 09:00 UTC
Hi!
I have created custom services with several characteristics on a other project.
When I debug the repo exemple on windows, I can see the custom service but can't access it's characteristics.

Tried on Android, it work fine.

Flutter 3.19.3
universal_ble 0.9.5

**Comment by fotiDim** [comment] 2024-03-23 19:30
@Regular89 on further inspection it does not seem to be a capabilities issue. Perhaps some bug in the code, not sure yet.
However, can you clarify if the issue is only with Characteristic discovery? You should still be able to read/write to characteristics that you know beforehand.

**Comment by fotiDim** [comment] 2024-03-28 08:52
Fixed in 0.9.6

**Closed by fotiDim** 2024-03-28 08:52 UTC
